# Generated by Django 4.2.16 on 2025-06-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('height_unit', models.CharField(default='cm', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('current_weight', models.FloatField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('food_allergies', models.CharField(blank=True, max_length=255)),
                ('cooking_skill', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True)),
                ('budget', models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('No restrictions', 'No restrictions')], max_length=30, null=True)),
                ('physical_activity', models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=20, null=True)),
                ('include_exercise', models.BooleanField(default=False)),
                ('meal_prep_time', models.CharField(blank=True, max_length=30)),
                ('meals_per_day', models.CharField(blank=True, max_length=20)),
                ('cooking_frequency', models.CharField(blank=True, max_length=50)),
                ('commitment_duration', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
