# Generated by Django 5.2.7 on 2025-10-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBuddy_app', '0002_meallog_dailyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='calories_goal',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='carbs_goal',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='fat_goal',
            field=models.FloatField(default=65),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='protein_goal',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date_logged',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='time_logged',
            field=models.TimeField(),
        ),
    ]
