# Generated by Django 5.2.7 on 2025-10-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitBuddy_app', '0003_dailyprogress_calories_goal_dailyprogress_carbs_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyProgress',
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
