# Generated by Django 5.2.7 on 2025-10-10 10:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBuddy_app', '0005_meallog_dailyprogress_weightlog'),
        ('recipes', '0003_recipe_diet_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weightlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='meallog',
            unique_together={('user', 'recipe', 'meal_type', 'date_logged')},
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date_logged',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='servings',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='DailyNutritionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='DailyProgress',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='calories_consumed',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='updated_at',
        ),
    ]
