# Generated by Django 4.2.16 on 2025-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet_types',
            field=models.CharField(blank=True, help_text='Comma-separated diet types', max_length=200, null=True),
        ),
    ]
